import { describe, it, expect, vi, beforeEach } from "vitest";

// Mock Prisma and other external deps before importing the module
vi.mock("@/lib/db/prisma", () => ({
  prisma: {
    case: {
      findUniqueOrThrow: vi.fn(),
    },
    detection: {
      findMany: vi.fn(),
    },
  },
}));

vi.mock("@/lib/data/org-config", () => ({
  getOrgBranding: vi.fn().mockResolvedValue({
    logoStorageKey: "",
    footerText: "Generated by Veil",
  }),
}));

vi.mock("@/lib/lgoima-grounds", () => ({
  getGroundById: vi.fn((id: string) => {
    const grounds: Record<string, { reference: string; label: string; description: string }> = {
      s7_2a: { reference: "s7(2)(a)", label: "Personal privacy", description: "Protect the privacy of natural persons" },
      s7_2fi: { reference: "s7(2)(f)(i)", label: "Free and frank opinions", description: "Maintain free and frank expression of opinions" },
    };
    return grounds[id] ?? null;
  }),
}));

import { buildWithholdingSchedule } from "../schedule";
import { prisma } from "@/lib/db/prisma";

const mockCase = {
  id: "case-1",
  reference: "LGOIMA-2025-042",
  requesterName: "Jane Smith",
};

function makeDetection(id: string, ground: string, docName: string, page: number) {
  return {
    id,
    type: "Name",
    text: "John Smith",
    page,
    confidence: 95,
    status: "accepted",
    appliedGround: ground,
    suggestedGround: ground,
    reasoning: "Personal name detected",
    document: { name: docName },
  };
}

describe("buildWithholdingSchedule", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    (prisma.batch.findUniqueOrThrow as ReturnType<typeof vi.fn>).mockResolvedValue(mockCase);
  });

  it("produces a valid PDF with zero detections", async () => {
    (prisma.detection.findMany as ReturnType<typeof vi.fn>).mockResolvedValue([]);

    const result = await buildWithholdingSchedule("case-1");

    expect(result.pdfBytes).toBeInstanceOf(Uint8Array);
    expect(result.pdfBytes.length).toBeGreaterThan(0);
    expect(result.itemCount).toBe(0);
  });

  it("produces a PDF with correct item count", async () => {
    const detections = [
      makeDetection("d1", "s7_2a", "Report.pdf", 1),
      makeDetection("d2", "s7_2a", "Report.pdf", 2),
      makeDetection("d3", "s7_2fi", "Minutes.pdf", 1),
    ];
    (prisma.detection.findMany as ReturnType<typeof vi.fn>).mockResolvedValue(detections);

    const result = await buildWithholdingSchedule("case-1");

    expect(result.itemCount).toBe(3);
    expect(result.pdfBytes).toBeInstanceOf(Uint8Array);
    expect(result.pdfBytes.length).toBeGreaterThan(0);
  });

  it("starts with a valid PDF header (%PDF)", async () => {
    (prisma.detection.findMany as ReturnType<typeof vi.fn>).mockResolvedValue([]);

    const result = await buildWithholdingSchedule("case-1");

    // PDF files start with %PDF
    const header = new TextDecoder().decode(result.pdfBytes.slice(0, 5));
    expect(header).toBe("%PDF-");
  });

  it("passes includeReasoning option through without error", async () => {
    const detections = [makeDetection("d1", "s7_2a", "Report.pdf", 1)];
    (prisma.detection.findMany as ReturnType<typeof vi.fn>).mockResolvedValue(detections);

    const result = await buildWithholdingSchedule("case-1", {
      includeReasoning: true,
    });

    expect(result.pdfBytes).toBeInstanceOf(Uint8Array);
    expect(result.itemCount).toBe(1);
  });

  it("passes documentIds filter through to prisma query", async () => {
    (prisma.detection.findMany as ReturnType<typeof vi.fn>).mockResolvedValue([]);

    await buildWithholdingSchedule("case-1", {
      documentIds: ["doc-1", "doc-2"],
    });

    expect(prisma.detection.findMany).toHaveBeenCalledWith(
      expect.objectContaining({
        where: expect.objectContaining({
          documentId: { in: ["doc-1", "doc-2"] },
          status: "accepted",
        }),
      }),
    );
  });

  it("queries all accepted detections when no documentIds filter", async () => {
    (prisma.detection.findMany as ReturnType<typeof vi.fn>).mockResolvedValue([]);

    await buildWithholdingSchedule("case-1");

    expect(prisma.detection.findMany).toHaveBeenCalledWith(
      expect.objectContaining({
        where: expect.objectContaining({
          document: { batchId: "case-1" },
          status: "accepted",
        }),
      }),
    );
  });
});
