import type { NextConfig } from "next";

/**
 * Server-action hash stability across deploys.
 *
 * Next.js encrypts server-action IDs with a per-build AES key. By
 * default that key is freshly generated by every `next build`, so two
 * deploys mint different IDs for the same action. Any client tab that
 * loaded the previous deploy then calls an action against the new one
 * gets `Failed to find Server Action "<hash>"` server-side, the action
 * promise rejects client-side, and (in our review surface) the popover
 * silently swallows the error — visible symptom is a "hung" submit.
 *
 * Mitigation has two pieces, both applied at build time:
 *
 *   1. `NEXT_SERVER_ACTIONS_ENCRYPTION_KEY` (env var, NOT a config
 *      field — Next 15.5.13 reads it directly via webpack DefinePlugin,
 *      see node_modules/next/dist/server/app-render/encryption-utils-server.js
 *      and node_modules/next/dist/build/webpack-config.js). Stable AES
 *      key shared across deploys → action IDs minted by any build are
 *      decryptable by any other build with the same key. Sourced from
 *      kv-veil-prototype/secrets/next-server-actions-key in CI.
 *
 *   2. `generateBuildId` (top-level NextConfig field). Stabilises
 *      `__NEXT_BUILD_ID` so per-deploy version-skew checks survive a
 *      blue/green rollout that runs the same source. We map it to the
 *      git SHA (passed in as `NEXT_BUILD_ID` at build time by
 *      .github/workflows/docker.yml). Returning `null` falls through
 *      to Next's default per-build hash — the safe fallback for local
 *      `next build` runs that don't set the env.
 *
 * Without (1), action hashes drift on every build even if (2) is set —
 * (1) is the load-bearing fix; (2) is supporting hygiene for CDN paths
 * and version checks. Local dev (`next dev --turbo`) regenerates
 * everything every server start so neither needs to be set unless you
 * want to match prod behaviour.
 *
 * If `NEXT_SERVER_ACTIONS_ENCRYPTION_KEY` is unset at build time, Next
 * silently falls back to the per-build random key. We surface a
 * non-blocking warning to make that fallback visible during build —
 * production deploys must always pass a stable key.
 */
if (
  process.env.NODE_ENV === "production" &&
  !process.env.NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
) {
  console.warn(
    "[next.config] NEXT_SERVER_ACTIONS_ENCRYPTION_KEY is unset — Next.js will mint a fresh per-build key. " +
      "Action hashes will drift across deploys. Set the env var (sourced from Key Vault in CI) before shipping.",
  );
}

const nextConfig: NextConfig = {
  output: "standalone",
  /**
   * Stable build ID — sourced from `NEXT_BUILD_ID` (CI passes the
   * commit SHA). `null` means "use Next's default" so unset-env local
   * builds keep working unchanged.
   */
  generateBuildId: () => process.env.NEXT_BUILD_ID ?? null,
  // pdfjs-dist 5.x ships as pure ESM. Next.js 15's webpack dev pipeline
  // crashes client-side at module init with "TypeError: Object.defineProperty
  // called on non-object" when loading pdfjs-dist/build/pdf.mjs.
  // transpilePackages is the documented mitigation and is kept here to
  // signal intent for future bundler configuration, but on Next 15.5.13 +
  // pdfjs-dist 5.4.296 it was not sufficient on its own (tried aliasing
  // to legacy/build, esmExternals: "loose", extensionAlias tweaks — none
  // resolved the webpack init error). Turbopack handles the same module
  // graph cleanly; the `dev` npm script therefore runs `next dev --turbo`.
  // Production `next build` + `next start` still use webpack and need a
  // separate smoke-check before Slice D flips the default VIEWER_MODE.
  // See Slice A PR body for the full rationale.
  transpilePackages: ["pdfjs-dist"],
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          {
            key: "X-Frame-Options",
            value: "DENY",
          },
          {
            key: "X-Content-Type-Options",
            value: "nosniff",
          },
          {
            key: "Referrer-Policy",
            value: "strict-origin-when-cross-origin",
          },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=()",
          },
          {
            key: "X-DNS-Prefetch-Control",
            value: "on",
          },
          {
            key: "Strict-Transport-Security",
            value: "max-age=31536000; includeSubDomains",
          },
          {
            key: "Content-Security-Policy",
            value: [
              "default-src 'self'",
              // Next.js dev server requires 'unsafe-eval' and 'unsafe-inline' for HMR
              process.env.NODE_ENV === "development"
                ? "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://unpkg.com"
                : "script-src 'self' 'unsafe-inline' https://unpkg.com",
              "worker-src 'self' blob:",
              "style-src 'self' 'unsafe-inline'",
              "img-src 'self' data: blob:",
              "font-src 'self' data:",
              "connect-src 'self' https://unpkg.com",
              "frame-ancestors 'none'",
              "base-uri 'self'",
              "form-action 'self'",
            ].join("; "),
          },
        ],
      },
    ];
  },
};
export default nextConfig;
