import { PrismaClient } from "../lib/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

/**
 * Umbra demo seed — Ministry of Demo (a fictional NZ central-government
 * agency).
 *
 *   1 admin user (Eugene Cash, eugene@datasing.nz, SSO admin)
 *   3 reviewer users with credentials login (NZ-flavoured names)
 *   3 sample Batches with auto-generated BATCH-2026-NNN references
 *   No documents — admin uploads real files during demos.
 *   Org identity + branding settings + setup-wizard completion.
 */

const connectionString =
  process.env.DATABASE_URL ||
  "postgresql://umbra:umbra_dev@localhost:5434/umbra";
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seeding Umbra database — Ministry of Demo scenario\n");

  // -------------------------------------------------------------------
  // Users
  // -------------------------------------------------------------------
  const users = [
    {
      id: "user-admin",
      name: "Eugene Cash",
      email: "eugene@datasing.nz",
      role: "admin",
      passwordHash: null,
      azureAdOid: null,
    },
    {
      id: "user-reviewer-1",
      name: "Maia Rangi",
      email: "maia.rangi@ministry-of-demo.govt.nz",
      role: "reviewer",
      passwordHash: await bcrypt.hash("demo1234", 10),
      azureAdOid: null,
    },
    {
      id: "user-reviewer-2",
      name: "Tom Whitaker",
      email: "tom.whitaker@ministry-of-demo.govt.nz",
      role: "reviewer",
      passwordHash: await bcrypt.hash("demo1234", 10),
      azureAdOid: null,
    },
    {
      id: "user-reviewer-3",
      name: "Aroha Ngata",
      email: "aroha.ngata@ministry-of-demo.govt.nz",
      role: "reviewer",
      passwordHash: await bcrypt.hash("demo1234", 10),
      azureAdOid: null,
    },
  ];

  for (const u of users) {
    await prisma.user.upsert({
      where: { id: u.id },
      update: {
        name: u.name,
        email: u.email,
        role: u.role,
        passwordHash: u.passwordHash,
      },
      create: u,
    });
  }
  console.log(`Users: ${users.length} created (1 admin + 3 reviewers)`);

  // -------------------------------------------------------------------
  // Org settings (identity + branding + signatory + retention)
  // -------------------------------------------------------------------
  const orgIdentity = {
    name: "Ministry of Demo",
    maoriName: "Te Manatū Whakaaturanga",
    abbreviation: "MoD",
    orgType: "Government Agency",
    address: "1 Demo Street, Wellington 6011",
    phone: "04 555 0100",
    email: "redactions@ministry-of-demo.govt.nz",
    website: "https://www.ministry-of-demo.govt.nz",
  };

  const orgSignatory = {
    name: "Eugene Cash",
    title: "Chief Privacy Officer",
    department: "Information Governance",
  };

  const orgBranding = {
    logoStorageKey: "",
    footerText: "Generated by Umbra — Ministry of Demo",
  };

  const confidenceThresholds = {
    high: 85,
    medium: 50,
  };

  const retentionConfig = {
    retentionDaysAfterCompletion: 14,
    gracePeriodDays: 7,
    autoRetentionEnabled: true,
  };

  const setupWizardState = {
    currentStep: 4,
    completedSteps: [0, 1, 2, 3, 4],
    completedAt: new Date().toISOString(),
  };

  const settings: Array<[string, object]> = [
    ["org_identity", orgIdentity],
    ["org_signatory", orgSignatory],
    ["org_branding", orgBranding],
    ["confidence_thresholds", confidenceThresholds],
    ["retention_config", retentionConfig],
    ["setup_wizard_state", setupWizardState],
    [
      "activation_status",
      {
        activated: true,
        activatedAt: new Date().toISOString(),
        activatedBy: "user-admin",
      },
    ],
  ];

  for (const [key, value] of settings) {
    await prisma.systemSetting.upsert({
      where: { key },
      update: { value, updatedBy: "seed" },
      create: { key, value, updatedBy: "seed" },
    });
  }
  console.log(`Settings: ${settings.length} keys upserted`);

  // -------------------------------------------------------------------
  // Sample batches
  // -------------------------------------------------------------------
  const year = new Date().getFullYear();
  const batches = [
    {
      reference: `BATCH-${year}-001`,
      name: "Q1 Public Submissions",
      status: "draft",
    },
    {
      reference: `BATCH-${year}-002`,
      name: "May 2026 Consultation Responses",
      status: "draft",
    },
    {
      reference: `BATCH-${year}-003`,
      name: "Working Group Correspondence",
      status: "draft",
    },
  ];

  for (const b of batches) {
    const existing = await prisma.batch.findUnique({
      where: { reference: b.reference },
    });
    if (!existing) {
      const created = await prisma.batch.create({ data: b });
      // Three pipeline stages — upload, review, export.
      for (const stage of ["upload", "review", "export"]) {
        await prisma.batchMilestone.create({
          data: {
            batchId: created.id,
            stage,
            completedAt: null,
          },
        });
      }
    }
  }
  console.log(
    `Batches: ${batches.length} created (no documents — admin uploads at demo time)`,
  );

  console.log("\nUmbra seed complete.");
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
