/**
 * Audit trail PDF generator for LGOIMA export packages.
 */

import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { prisma } from "@/lib/db/prisma";
import { getOrgBranding } from "@/lib/data/org-config";

export async function buildAuditTrailPdf(caseId: string): Promise<Uint8Array> {
  const [caseData, orgBranding] = await Promise.all([
    prisma.case.findUniqueOrThrow({ where: { id: caseId } }),
    getOrgBranding(),
  ]);

  const entries = await prisma.auditEntry.findMany({
    where: { caseId },
    orderBy: { timestamp: "asc" },
  });

  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const monoFont = await pdfDoc.embedFont(StandardFonts.Courier);
  const pageWidth = 595;
  const pageHeight = 842;
  const margin = 50;

  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let yPos = pageHeight - margin;

  // Title
  yPos -= 20;
  page.drawText("AUDIT TRAIL", {
    x: margin,
    y: yPos,
    size: 18,
    font: boldFont,
    color: rgb(0, 0, 0),
  });
  yPos -= 20;
  page.drawText(`Case: ${caseData.reference}`, {
    x: margin,
    y: yPos,
    size: 11,
    font,
    color: rgb(0.3, 0.3, 0.3),
  });
  yPos -= 16;
  page.drawText(`Generated: ${new Date().toISOString()}`, {
    x: margin,
    y: yPos,
    size: 9,
    font: monoFont,
    color: rgb(0.4, 0.4, 0.4),
  });
  yPos -= 14;
  page.drawText(`Total Entries: ${entries.length}`, {
    x: margin,
    y: yPos,
    size: 9,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });

  yPos -= 25;
  page.drawLine({
    start: { x: margin, y: yPos },
    end: { x: pageWidth - margin, y: yPos },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  });
  yPos -= 20;

  // Entries
  for (const entry of entries) {
    if (yPos < margin + 60) {
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPos = pageHeight - margin;
    }

    // Timestamp
    const ts = entry.timestamp.toISOString().replace("T", " ").slice(0, 19);
    page.drawText(ts, {
      x: margin,
      y: yPos,
      size: 8,
      font: monoFont,
      color: rgb(0.4, 0.4, 0.4),
    });

    // User
    page.drawText(`${entry.userName} (${entry.userRole})`, {
      x: margin + 150,
      y: yPos,
      size: 8,
      font: boldFont,
      color: rgb(0.2, 0.2, 0.2),
    });
    yPos -= 12;

    // Type + description
    page.drawText(`[${entry.type}]`, {
      x: margin + 10,
      y: yPos,
      size: 7,
      font: monoFont,
      color: rgb(0.5, 0.5, 0.5),
    });
    const desc = entry.description.length > 80
      ? entry.description.slice(0, 80) + "..."
      : entry.description;
    page.drawText(desc, {
      x: margin + 90,
      y: yPos,
      size: 8,
      font,
      color: rgb(0, 0, 0),
    });
    yPos -= 12;

    // Target
    if (entry.target) {
      page.drawText(`Target: ${entry.target}`, {
        x: margin + 10,
        y: yPos,
        size: 7,
        font,
        color: rgb(0.5, 0.5, 0.5),
      });
      yPos -= 10;
    }

    // Detail
    if (entry.detail) {
      const detail = entry.detail.length > 100
        ? entry.detail.slice(0, 100) + "..."
        : entry.detail;
      page.drawText(`Detail: ${detail}`, {
        x: margin + 10,
        y: yPos,
        size: 7,
        font,
        color: rgb(0.5, 0.5, 0.5),
      });
      yPos -= 10;
    }

    // Separator
    yPos -= 6;
    page.drawLine({
      start: { x: margin, y: yPos },
      end: { x: pageWidth - margin, y: yPos },
      thickness: 0.3,
      color: rgb(0.9, 0.9, 0.9),
    });
    yPos -= 8;
  }

  // Footer
  if (yPos < margin + 20) {
    page = pdfDoc.addPage([pageWidth, pageHeight]);
    yPos = pageHeight - margin;
  }
  yPos -= 15;
  page.drawText("This audit trail is an immutable record of all actions taken on this case.", {
    x: margin,
    y: yPos,
    size: 7,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });
  yPos -= 10;
  const auditFooter = orgBranding.footerText || "Generated by Veil LGOIMA Disclosure Platform";
  page.drawText(auditFooter, {
    x: margin,
    y: yPos,
    size: 7,
    font,
    color: rgb(0.6, 0.6, 0.6),
  });

  pdfDoc.setTitle(`Audit Trail — ${caseData.reference}`);
  pdfDoc.setCreator("Veil LGOIMA Disclosure Platform");
  pdfDoc.setProducer(orgBranding.footerText || "Veil LGOIMA Disclosure Platform");

  return pdfDoc.save();
}
