/**
 * Audit Timeline PDF generator.
 *
 * Per-document timeline of every handling event captured in the
 * immutable audit trail: upload, processing, review, sign-off,
 * export. The output is a PDF suitable for inclusion in a batch's
 * export package and as standalone evidence of how each document was
 * touched.
 */

import { PDFDocument, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { embedFonts } from "./pdf-fonts";
import { prisma } from "@/lib/db/prisma";
import { getOrgBranding } from "@/lib/data/org-config";
import { embedOrgLogo } from "./logo-helper";

export interface AuditTimelineResult {
  pdfBytes: Uint8Array;
  documentCount: number;
}

const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN = 50;
const MAX_TEXT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

interface DrawContext {
  pdfDoc: PDFDocument;
  font: PDFFont;
  boldFont: PDFFont;
  monoFont: PDFFont;
  page: PDFPage;
  yPos: number;
}

function ensureSpace(ctx: DrawContext, needed: number): DrawContext {
  if (ctx.yPos < MARGIN + needed) {
    ctx.page = ctx.pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    ctx.yPos = PAGE_HEIGHT - MARGIN;
  }
  return ctx;
}

function drawText(
  ctx: DrawContext,
  text: string,
  options: {
    x?: number;
    size?: number;
    font?: PDFFont;
    color?: ReturnType<typeof rgb>;
  } = {},
) {
  const x = options.x ?? MARGIN;
  const size = options.size ?? 9;
  const font = options.font ?? ctx.font;
  const color = options.color ?? rgb(0, 0, 0);

  const maxChars = Math.floor(MAX_TEXT_WIDTH / (size * 0.5));
  const truncated = text.length > maxChars ? text.slice(0, maxChars - 3) + "..." : text;

  ctx.page.drawText(truncated, { x, y: ctx.yPos, size, font, color });
}

function formatTimestamp(date: Date): string {
  return date.toISOString().replace("T", " ").slice(0, 19) + " UTC";
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export async function buildAuditTimeline(
  batchId: string,
  generatedBy: string,
): Promise<AuditTimelineResult> {
  const [batchData, orgBranding] = await Promise.all([
    prisma.batch.findUniqueOrThrow({ where: { id: batchId } }),
    getOrgBranding(),
  ]);

  const [documents, allAuditEntries] = await Promise.all([
    prisma.document.findMany({
      where: { batchId },
      orderBy: { name: "asc" },
      include: {
        detections: {
          select: { id: true, status: true },
        },
      },
    }),
    prisma.auditEntry.findMany({
      where: { batchId },
      orderBy: { timestamp: "asc" },
    }),
  ]);

  const pdfDoc = await PDFDocument.create();
  const { regular: font, bold: boldFont, mono: monoFont } = await embedFonts(pdfDoc);

  const ctx: DrawContext = {
    pdfDoc,
    font,
    boldFont,
    monoFont,
    page: pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]),
    yPos: PAGE_HEIGHT - MARGIN,
  };

  const logo = await embedOrgLogo(pdfDoc);
  if (logo) {
    ctx.page.drawImage(logo.image, {
      x: PAGE_WIDTH - MARGIN - logo.width,
      y: ctx.yPos - logo.height + 10,
      width: logo.width,
      height: logo.height,
    });
  }

  ctx.yPos -= 20;
  drawText(ctx, "AUDIT TIMELINE", {
    size: 20,
    font: boldFont,
    color: rgb(0, 0, 0),
  });

  ctx.yPos -= 28;
  drawText(ctx, `Batch Reference: ${batchData.reference}`, {
    size: 12,
    font: boldFont,
    color: rgb(0.2, 0.2, 0.2),
  });

  ctx.yPos -= 18;
  drawText(
    ctx,
    `Generation Date: ${new Date().toLocaleDateString("en-NZ", { day: "numeric", month: "long", year: "numeric" })}`,
    { size: 10, color: rgb(0.3, 0.3, 0.3) },
  );

  ctx.yPos -= 16;
  drawText(ctx, `Generated By: ${generatedBy}`, {
    size: 10,
    color: rgb(0.3, 0.3, 0.3),
  });

  ctx.yPos -= 16;
  drawText(ctx, `Total Documents: ${documents.length}`, {
    size: 10,
    color: rgb(0.3, 0.3, 0.3),
  });

  ctx.yPos -= 20;
  ctx.page.drawLine({
    start: { x: MARGIN, y: ctx.yPos },
    end: { x: PAGE_WIDTH - MARGIN, y: ctx.yPos },
    thickness: 1,
    color: rgb(0.7, 0.7, 0.7),
  });
  ctx.yPos -= 10;

  ctx.yPos -= 10;
  drawText(
    ctx,
    "This report lists every handling event captured for each document in this batch:",
    { size: 8, color: rgb(0.4, 0.4, 0.4) },
  );
  ctx.yPos -= 12;
  drawText(
    ctx,
    "upload, automated processing, review actions, sign-off, and export.",
    { size: 8, color: rgb(0.4, 0.4, 0.4) },
  );
  ctx.yPos -= 12;
  drawText(ctx, "Each entry is sourced from the immutable audit trail.", {
    size: 8,
    color: rgb(0.4, 0.4, 0.4),
  });

  ctx.yPos -= 25;

  for (let docIndex = 0; docIndex < documents.length; docIndex++) {
    const doc = documents[docIndex];

    ensureSpace(ctx, 120);

    ctx.page.drawLine({
      start: { x: MARGIN, y: ctx.yPos },
      end: { x: PAGE_WIDTH - MARGIN, y: ctx.yPos },
      thickness: 0.8,
      color: rgb(0.6, 0.6, 0.6),
    });
    ctx.yPos -= 18;

    drawText(ctx, `Document ${docIndex + 1} of ${documents.length}`, {
      size: 8,
      font: monoFont,
      color: rgb(0.5, 0.5, 0.5),
    });
    ctx.yPos -= 14;

    drawText(ctx, doc.name, {
      size: 12,
      font: boldFont,
      color: rgb(0.1, 0.1, 0.1),
    });
    ctx.yPos -= 16;

    const metaItems = [
      `File Type: ${doc.fileType}`,
      `Pages: ${doc.pageCount}`,
      `Size: ${formatFileSize(doc.sizeBytes)}`,
      `Status: ${doc.status}`,
    ];
    drawText(ctx, metaItems.join("   |   "), {
      size: 8,
      color: rgb(0.4, 0.4, 0.4),
    });
    ctx.yPos -= 14;

    if (doc.contentHash) {
      drawText(ctx, `Content Hash: ${doc.contentHash}`, {
        size: 7,
        font: monoFont,
        color: rgb(0.5, 0.5, 0.5),
      });
      ctx.yPos -= 12;
    }

    if (doc.duplicateGroup) {
      drawText(ctx, `Duplicate Group: ${doc.duplicateGroup}`, {
        size: 7,
        font: monoFont,
        color: rgb(0.5, 0.5, 0.5),
      });
      ctx.yPos -= 12;
    }

    const accepted = doc.detections.filter((d) => d.status === "accepted").length;
    const rejected = doc.detections.filter((d) => d.status === "rejected").length;
    const pending = doc.detections.filter((d) => d.status === "pending").length;
    drawText(
      ctx,
      `Detections: ${accepted} accepted, ${rejected} rejected, ${pending} pending (${doc.detections.length} total)`,
      { size: 8, color: rgb(0.3, 0.3, 0.3) },
    );
    ctx.yPos -= 18;

    drawText(ctx, "TIMELINE", {
      size: 9,
      font: boldFont,
      color: rgb(0.2, 0.2, 0.2),
    });
    ctx.yPos -= 14;

    const timeline: Array<{ timestamp: Date; event: string; actor: string; detail?: string }> = [];

    timeline.push({
      timestamp: doc.createdAt,
      event: "Uploaded",
      actor: "System",
      detail: `File: ${doc.name} (${doc.fileType}, ${formatFileSize(doc.sizeBytes)})`,
    });

    if (doc.processingStartedAt) {
      timeline.push({
        timestamp: doc.processingStartedAt,
        event: "Processing Started",
        actor: "Umbra",
      });
    }

    if (doc.processingCompletedAt) {
      const parts: string[] = [];
      if (doc.extractionMs != null) parts.push(`Extraction: ${doc.extractionMs}ms`);
      if (doc.patternDetectionMs != null) parts.push(`Patterns: ${doc.patternDetectionMs}ms`);
      if (doc.aiDetectionMs != null) parts.push(`AI Detection: ${doc.aiDetectionMs}ms`);
      if (doc.totalProcessingMs != null) parts.push(`Total: ${doc.totalProcessingMs}ms`);

      timeline.push({
        timestamp: doc.processingCompletedAt,
        event: "Processing Completed",
        actor: "Umbra",
        detail: parts.length > 0 ? parts.join(", ") : undefined,
      });
    }

    const docAuditEntries = allAuditEntries.filter((entry) => {
      const target = entry.target?.toLowerCase() ?? "";
      const desc = entry.description?.toLowerCase() ?? "";
      const docNameLower = doc.name.toLowerCase();
      return target.includes(docNameLower) || desc.includes(docNameLower);
    });

    for (const entry of docAuditEntries) {
      const eventType = categorizeAuditType(entry.type);
      if (eventType) {
        timeline.push({
          timestamp: entry.timestamp,
          event: eventType,
          actor: `${entry.userName} (${entry.userRole})`,
          detail: entry.description,
        });
      }
    }

    timeline.sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime());

    for (const entry of timeline) {
      ensureSpace(ctx, 36);

      drawText(ctx, formatTimestamp(entry.timestamp), {
        size: 7,
        font: monoFont,
        color: rgb(0.4, 0.4, 0.4),
      });

      drawText(ctx, `${entry.event}`, {
        x: MARGIN + 160,
        size: 8,
        font: boldFont,
        color: rgb(0.2, 0.2, 0.2),
      });

      drawText(ctx, entry.actor, {
        x: MARGIN + 320,
        size: 7,
        color: rgb(0.4, 0.4, 0.4),
      });

      ctx.yPos -= 11;

      if (entry.detail) {
        ensureSpace(ctx, 20);
        const detailText =
          entry.detail.length > 100 ? entry.detail.slice(0, 100) + "..." : entry.detail;
        drawText(ctx, detailText, {
          x: MARGIN + 20,
          size: 7,
          color: rgb(0.5, 0.5, 0.5),
        });
        ctx.yPos -= 10;
      }

      ctx.yPos -= 3;
      ctx.page.drawLine({
        start: { x: MARGIN + 10, y: ctx.yPos },
        end: { x: PAGE_WIDTH - MARGIN - 10, y: ctx.yPos },
        thickness: 0.2,
        color: rgb(0.92, 0.92, 0.92),
      });
      ctx.yPos -= 6;
    }

    if (timeline.length === 0) {
      drawText(ctx, "No audit trail events recorded for this document.", {
        size: 8,
        color: rgb(0.5, 0.5, 0.5),
      });
      ctx.yPos -= 14;
    }

    ctx.yPos -= 15;
  }

  ensureSpace(ctx, 50);

  ctx.yPos -= 10;
  ctx.page.drawLine({
    start: { x: MARGIN, y: ctx.yPos },
    end: { x: PAGE_WIDTH - MARGIN, y: ctx.yPos },
    thickness: 0.5,
    color: rgb(0.8, 0.8, 0.8),
  });
  ctx.yPos -= 14;

  drawText(
    ctx,
    "This audit timeline is an immutable record of all handling events for documents in this batch.",
    { size: 7, color: rgb(0.5, 0.5, 0.5) },
  );
  ctx.yPos -= 12;

  const footerText = orgBranding.footerText || "Generated by Umbra";
  drawText(ctx, footerText, {
    size: 7,
    color: rgb(0.6, 0.6, 0.6),
  });

  pdfDoc.setTitle(`Audit Timeline — ${batchData.reference}`);
  pdfDoc.setCreator("Umbra");
  pdfDoc.setProducer(orgBranding.footerText || "Umbra");
  pdfDoc.setSubject(`Audit Timeline for batch ${batchData.reference}`);

  const pdfBytes = await pdfDoc.save();

  return {
    pdfBytes,
    documentCount: documents.length,
  };
}

/**
 * Map raw audit entry types to human-readable timeline labels.
 * Returns null for audit types that aren't relevant to the timeline.
 */
function categorizeAuditType(type: string): string | null {
  const mapping: Record<string, string> = {
    "document-upload": "Document Uploaded",
    "document-uploaded": "Document Uploaded",
    "processing-started": "Processing Started",
    "processing-start": "Processing Started",
    "processing-complete": "Processing Completed",
    "processing-completed": "Processing Completed",
    "processing-error": "Processing Error",
    "detection-accepted": "Detection Reviewed (Accepted)",
    "detection-rejected": "Detection Reviewed (Rejected)",
    "detection-reviewed": "Detection Reviewed",
    "detection-update": "Detection Updated",
    "review-submitted": "Review Submitted",
    "review-started": "Review Started",
    "sign-off": "Sign-Off",
    "signed-off": "Sign-Off",
    "export-generated": "Export Package Generated",
    "export-started": "Export Started",
    "redaction-verification": "Redaction Verified",
    "document-assigned": "Reviewer Assigned",
    "status-change": "Status Changed",
  };

  return mapping[type] ?? null;
}
